[
  {
    id: 830362723,
    parentId: -1,
    isPreview: false,
    name: 'DCE - Consumo',
    createdAt: 1607353571700,
    updatedAt: 1608143542033,
    widgets: [
      {
        type: 'ENHANCED_GRAPH',
        id: 127136,
        x: 0,
        y: 5,
        color: 79755519,
        width: 8,
        height: 4,
        tabId: 0,
        label: 'Gasto de Energia (Potência)',
        isDefaultColor: false,
        dataStreams: [
          {
            title: 'Ampères',
            graphType: 'LINE',
            color: 79755519,
            targetId: 0,
            pin: {
              pin: 1,
              pwmMode: false,
              rangeMappingOn: false,
              pinType: 'VIRTUAL',
              min: 0,
              max: 1023,
            },
            flip: 511,
            yAxisMin: 0,
            yAxisMax: 100,
            showYAxis: true,
            suffix: 'A',
            cubicSmoothingEnabled: false,
            connectMissingPointsEnabled: false,
            isPercentMaxMin: true,
            yAxisScale: 'AUTO',
            delta: 0,
            userDeltaModifyAllowed: false,
            maximumFractionDigits: 2,
          },
          {
            title: 'Watts',
            graphType: 'LINE',
            color: 1602017535,
            targetId: 0,
            pin: {
              pin: 2,
              pwmMode: false,
              rangeMappingOn: false,
              pinType: 'VIRTUAL',
              min: 0,
              max: 1023,
            },
            flip: 511,
            yAxisMin: 0,
            yAxisMax: 100,
            showYAxis: true,
            suffix: 'W',
            cubicSmoothingEnabled: false,
            connectMissingPointsEnabled: false,
            isPercentMaxMin: true,
            yAxisScale: 'AUTO',
            delta: 0,
            userDeltaModifyAllowed: false,
            maximumFractionDigits: 2,
          },
        ],
        period: 'LIVE',
        textAlignment: 'LEFT',
        fontSize: 'MEDIUM',
        stacking: 'NO_STACKING',
        showTitle: true,
        showLegend: true,
        yAxisValues: false,
        xAxisValues: false,
        showXAxis: false,
        allowFullScreen: true,
        overrideYAxis: false,
        hideGradient: false,
        yAxisMin: 0,
        yAxisMax: 0,
        isPercentMaxMin: false,
        goalLine: 'GOAL',
        selectedPeriods: [
          'LIVE',
          'ONE_HOUR',
          'SIX_HOURS',
          'N_DAY',
          'N_WEEK',
          'N_MONTH',
          'N_THREE_MONTHS',
        ],
      },
      {
        type: 'GAUGE',
        id: 141062,
        x: 4,
        y: 1,
        color: 1602017535,
        width: 4,
        height: 3,
        tabId: 0,
        label: 'Potência [W]',
        isDefaultColor: false,
        deviceId: 0,
        pinType: 'VIRTUAL',
        pin: 2,
        pwmMode: false,
        rangeMappingOn: false,
        min: 0,
        max: 800,
        value: '4.4400931',
        frequency: 0,
        valueFormatting: '/pin/"Watts"',
        fontSize: 'LARGE',
      },
      {
        type: 'GAUGE',
        id: 40781,
        x: 0,
        y: 1,
        color: 79755519,
        width: 4,
        height: 3,
        tabId: 0,
        label: 'CORRENTE [A]',
        isDefaultColor: false,
        deviceId: 0,
        pinType: 'VIRTUAL',
        pin: 1,
        pwmMode: false,
        rangeMappingOn: false,
        min: 0,
        max: 10,
        value: '0.0374623',
        frequency: 0,
        valueFormatting: '/pin/"Amps"',
        fontSize: 'LARGE',
      },
      {
        type: 'DIGIT4_DISPLAY',
        id: 74492,
        x: 2,
        y: 4,
        color: -308477697,
        width: 3,
        height: 1,
        tabId: 0,
        label: 'ÚLTIMA HORA [kWh]',
        isDefaultColor: false,
        deviceId: 0,
        pinType: 'VIRTUAL',
        pin: 1,
        pwmMode: false,
        rangeMappingOn: false,
        min: 0,
        max: 1023,
        value: '0.0374623',
        frequency: 0,
        fontSize: 'LARGE',
      },
      {
        type: 'DIGIT4_DISPLAY',
        id: 130577,
        x: 5,
        y: 4,
        color: -308477697,
        width: 3,
        height: 1,
        tabId: 0,
        label: 'ÚLTIMO DIA [kWh]',
        isDefaultColor: false,
        deviceId: 0,
        pinType: 'VIRTUAL',
        pin: 1,
        pwmMode: false,
        rangeMappingOn: false,
        min: 0,
        max: 1023,
        value: '0.0374623',
        frequency: 0,
        fontSize: 'LARGE',
      },
      {
        type: 'RTC',
        id: 51456,
        x: 0,
        y: 4,
        color: -1,
        width: 2,
        height: 1,
        tabId: 0,
        isDefaultColor: false,
        tzName: 'America/Sao_Paulo',
      },
    ],
    devices: [
      {
        id: 0,
        name: 'DCE - Consumo',
        boardType: 'ESP32 Dev Board',
        vendor: 'New Device',
        connectionType: 'WI_FI',
        isUserIcon: false,
      },
    ],
    theme: 'Blynk',
    keepScreenOn: false,
    isAppConnectedOn: false,
    isNotificationsOff: false,
    isShared: false,
    isActive: false,
    widgetBackgroundOn: false,
    color: 0,
    isDefaultColor: true,
  },
];
